{
 "title": "Jobs & Salaries in Data Science",
 "description": "This is a sample dashboard which draws analysis on the job market of data science with its salaries comparisions",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Entry Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select experience_level,count(*) from public.jobs_in_data where experience_level ='Entry-level' group by 1 ;"
    }
   ]
  },
  {
   "title": "Mid Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "select experience_level,count(*) from public.jobs_in_data where experience_level ='Mid-level' group by 1 ;"
    }
   ]
  },
  {
   "title": "Category wise Salaries",
   "type": "piechart",
   "description": "This shows with in the data set, Machine learning and data scientist researchers have the best average salary rate across the world",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select job_category,round(avg(salary),0) as average_salary from public.jobs_in_data group by 1 order by 2 desc;"
    }
   ]
  },
  {
   "title": "Work setting wise salaries",
   "type": "gauge",
   "description": "This shows that as compared to hybrid , both Remote and In-Person has high average salary rates.",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select work_setting,round(avg(salary_in_usd),0) as average_salary,count(*) samples \r\nfrom public.jobs_in_data group by 1 \r\norder by average_salary desc;"
    }
   ]
  },
  {
   "title": "Senior Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select experience_level,count(*) from public.jobs_in_data where experience_level ='Senior' group by 1 ;"
    }
   ]
  },
  {
   "title": "Executive Level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "targets": [
    {
     "rawSql": "select experience_level,count(*) from public.jobs_in_data where experience_level ='Executive' group by 1 ;"
    }
   ]
  },
  {
   "title": "Country wise sample size comparison",
   "type": "geomap",
   "description": "This data set contains data from across the world, Visualizing in this world map the sample size across different countries.",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select company_location as country,count(*) as datasetcounts FROM public.jobs_in_data group by 1 order by 1 asc;"
    }
   ]
  },
  {
   "title": "Country wise Salaries",
   "type": "barchart",
   "description": "This captures only those countries which have sample size greater than 50, showing USA has the best average salaries across the sample data",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "select company_location,round(avg(salary),0) as average_salary,count(*)::text samples \r\nfrom public.jobs_in_data group by 1 \r\nhaving count(*) > 50\r\norder by average_salary desc;"
    }
   ]
  },
  {
   "title": "Job Title wise roles",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select job_title ,count(*) total_roles from public.jobs_in_data \r\ngroup by 1 order by 2 desc;"
    }
   ]
  },
  {
   "title": "Raw Data",
   "type": "table",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT work_year, job_title, job_category, salary_currency, salary, salary_in_usd, employee_residence, experience_level, employment_type, work_setting, company_location, company_size\r\nFROM public.jobs_in_data;"
    }
   ]
  }
 ]
}